import exception.CatchException;
import view.View;
public class Main {
    public static void main(String[] args) throws CatchException
    {
        View.UI();
    }
}




